export const initialState = {
  posts: {
    data: [
      {
        id: '1',
        title: 'Zastępstwo Adwokackie',
        text: 'W Sądzie Rejonowym',
        created: '2021-11-28',
        updated: '2021-11-28',
        email: 'johnDoe@mail.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/6254378/pexels-photo-6254378.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        price: 250,
        phone: 123456789,
        location: 'Gdańsk, Poland',
      },
      {
        id: '2',
        title: 'Zdjęcia',
        text: 'Oferuję zdjęcia w prokuraturze - W dniu 25.12.2021 r. Cena do ustalenia, minimum 100 zł/godzinę + VAT',
        created: '2021-11-28',
        updated: '2021-11-28',
        email: 'Michal@dev.pl',
        status: 'published',
        image: 'https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        price: 100,
        phone: 987654321,
        location: 'Warsaw, Poland',
      },
      {
        id: '3',
        title: 'Zatrudnię Aplikanta!',
        text: 'W kancelarii radcowskiej',
        created: '2021-11-27',
        updated: '2021-11-28',
        email: 'johnDoe@mail.com',
        status: 'closed',
        image: '',
        price: 2500,
        phone: 111222333,
        location: 'Działdowo, Poland',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  user: {
    status: 'logged-in',
    email: 'Michal@dev.pl',
  },
};
